INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
SELECT 'CCOSTO_CE','Centro de costo por defecto para consulta externa','Alfanumerica',''

GO
--ALTER TABLE CIT ADD CNSRESERVA VARCHAR(20) DEFAULT NULL
--GO