IF OBJECT_ID('SPK_TER','P') IS NOT NULL DROP PROCEDURE SPK_TER
GO
CREATE PROCEDURE SPK_TER
	@IDTERCERO VARCHAR(20) = NULL,
	@IDCATEGORIA VARCHAR(20) = NULL
WITH ENCRYPTION
AS
BEGIN

	SELECT * FROM TER 
	WHERE IDTERCERO IN (
		SELECT IDTERCERO FROM TEXCA
		WHERE IDCATEGORIA = CASE WHEN ISNULL(@IDCATEGORIA,'')='' THEN IDCATEGORIA ELSE @IDCATEGORIA END
	)
	AND IDTERCERO IN (SELECT DISTINCT IDTERCERO FROM PPT)
END
GO
EXEC SPK_TER '','CON'

--FECHASOL
--IDAFILIADO
--NUMCARNET
--IDSERVICIO--SERTOT1
--IDCONTRATANTE
--IDPLAN
--VALOR
--VALORCOPAGO
--TIPOCOPAGO Cambia valor C
--SERTOT1
--IDEMEDICA
--IDTERCEROCA


--Programas Especiales
