IF OBJECT_ID('SPK_SER','P') IS NOT NULL DROP PROCEDURE SPK_SER
GO
CREATE PROCEDURE SPK_SER
	@IDAFILIADO VARCHAR(20),
	@TIPO_DOC VARCHAR(20),
	@IDMEDICO VARCHAR(20)
WITH ENCRYPTION 
AS
DECLARE @IDEMEDICA	VARCHAR(20)
DECLARE @SEXO VARCHAR(1)='A'
BEGIN
	SELECT @IDEMEDICA = IDEMEDICA FROM MED WHERE IDMEDICO=@IDMEDICO
	SELECT @SEXO=SEXO FROM AFI WHERE IDAFILIADO=@IDAFILIADO AND TIPO_DOC=@TIPO_DOC

	SELECT SER.* FROM MESS INNER JOIN SER ON SER.IDSERVICIO=MESS.IDSERVICIO AND IDEMEDICA=@IDEMEDICA
	AND (ISNULL(LEFT(@SEXO,1),'A')='M' OR ISNULL(SER.SEXO,'A')='A')
	AND SER.IDSERVICIO NOT IN (SELECT IDSERVICIO FROM CIT WHERE FECHA>GETDATE() AND IDAFILIADO=@IDAFILIADO)
END
GO
EXEC SPK_SER @IDAFILIADO = '690989', @TIPO_DOC = 'CE', @IDMEDICO = '73125209'