--SELECT * FROM SYS.OBJECTS WHERE NAME LIKE '%CIT%'
IF OBJECT_ID('SPK_CIT_DEL','P') IS NOT NULL DROP PROCEDURE SPK_CIT_DEL
GO
CREATE PROCEDURE SPK_CIT_DEL
	@CONSECUTIVO VARCHAR(20)
WITH ENCRYPTION
AS
BEGIN
	
	UPDATE CIT SET
		IDAFILIADO=NULL, NUMCARNET=NULL
		--,FECHASOL=GETDATE(), TIPOCITA = 'Cita', TIPOSOLICITUD = 'Web'
		,IDSERVICIO=NULL
		--, ATENCION = 'Ambulatoria'
		,IDCONTRATANTE=NULL
		,IDMEDICO=NULL, IDPLAN=NULL, TELEFONOAVISO=NULL--, USUARIO='KRYSTALOS', TIPOCOPAGO='C'
		,CCOSTO=NULL, IDEMEDICA=NULL, IDTERCEROCA=NULL, VALORTOTAL = NULL
	WHERE CONSECUTIVO=@CONSECUTIVO

END
GO
