IF OBJECT_ID('SPK_OCU','P') IS NOT NULL DROP PROCEDURE SPK_OCU
GO
CREATE PROCEDURE SPK_OCU
	@IDOCUPACION VARCHAR(20) = NULL
WITH ENCRYPTION
AS
BEGIN
	SELECT OCUPACION IDOCUPACION, DBO.FNK_CAPITALIZARTEXTO(DESCRIPCION) AS OCUPACION 
	FROM OCU 
	WHERE OCU.OCUPACION = CASE WHEN ISNULL(@IDOCUPACION,'')='' THEN OCU.OCUPACION ELSE @IDOCUPACION END
	ORDER BY OCU.DESCRIPCION
END
GO

EXEC SPK_OCU