IF OBJECT_ID('SPK_CIUB','P') IS NOT NULL DROP PROCEDURE SPK_CIUB
GO
CREATE PROCEDURE SPK_CIUB
	@IDBARRIO VARCHAR(20) = NULL
	,@IDCIUDAD VARCHAR(20) = NULL
	,@IDDEPARTAMENTO VARCHAR(20) = NULL
WITH ENCRYPTION
AS
BEGIN
	SELECT IDBARRIO, [dbo].[FNK_CapitalizarTexto](CIUB.NOMBRE) AS BARRIO
		,CIU.CIUDAD AS IDCIUDAD, [dbo].[FNK_CapitalizarTexto](CIU.NOMBRE) AS CIUDAD
		,DEP.DPTO AS IDDEPARTAMENTO, [dbo].[FNK_CapitalizarTexto](DEP.NOMBRE) AS DEPARTAMENTO
		,PAIS
	FROM CIUB INNER JOIN CIU ON CIU.CIUDAD=CIUB.CIUDAD INNER JOIN DEP ON DEP.DPTO=CIU.DPTO
	WHERE IDBARRIO=CASE WHEN ISNULL(@IDBARRIO,'')='' THEN IDBARRIO ELSE @IDBARRIO END
	AND CIU.CIUDAD=CASE WHEN ISNULL(@IDCIUDAD,'')='' THEN CIU.CIUDAD ELSE @IDCIUDAD END
	AND DEP.DPTO = CASE WHEN ISNULL(@IDDEPARTAMENTO,'')='' THEN DEP.DPTO ELSE @IDDEPARTAMENTO END
	ORDER BY IDDEPARTAMENTO, IDCIUDAD, BARRIO
END
GO

EXEC SPK_CIUB --'15005'
