--SELECT * FROM SYS.OBJECTS WHERE NAME LIKE '%CIT%'
IF OBJECT_ID('SPK_CIT_ADD','P') IS NOT NULL DROP PROCEDURE SPK_CIT_ADD
GO
CREATE PROCEDURE SPK_CIT_ADD
	@CONSECUTIVO VARCHAR(20),
	@IDAFILIADO VARCHAR(20),
	@IDMEDICO VARCHAR(20),
	@IDSERVICIO VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @NUMCARNET AS VARCHAR(20)
DECLARE @IDCONTRATANTE AS VARCHAR(20)
DECLARE @IDPLAN AS VARCHAR(20)
DECLARE @TELEFONOAVISO AS VARCHAR(30)
DECLARE @IDAREA AS VARCHAR(20)
DECLARE @IDAREAH AS VARCHAR(20)
DECLARE @CCOSTO AS VARCHAR(20)
DECLARE @FECHA AS DATETIME
DECLARE @IDEMEDICA AS VARCHAR(20)

BEGIN
	
	--DATOS DEL AFILIADO
	SELECT @NUMCARNET=NUMCARNET, @IDCONTRATANTE=IDADMINISTRADORA,@IDPLAN=IDPLAN, @TELEFONOAVISO = CASE WHEN ISNULL(CELULAR,'')='' THEN TELEFONORES ELSE CELULAR END
	FROM AFI WHERE IDAFILIADO=@IDAFILIADO

	--DATOS DE LA CITA
	SELECT @FECHA=FECHA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO


	-- AREA FUNCIONAL DEL SERVICIO
	SELECT @CCOSTO=dbo.FNK_VALORVARIABLE('CCOSTO_CE')

	SELECT TOP 1 @IDAREAH=IDAREAH, @IDAREA=IDAREA 
	FROM AFU 
	WHERE ISNULL(CE,0)=1 
	AND IDAREA IN (
		SELECT DISTINCT IDAREACA 
		FROM SERTOT1 
		WHERE IDSERVICIO = @IDSERVICIO
		AND @FECHA BETWEEN FECHAINIFD AND FECHAFINFD
		AND @FECHA BETWEEN FECHAINI AND FECHAFIN
		AND IDTERCERO = @IDCONTRATANTE)
	
	--DATOS DEL MEDICO
	SELECT @IDEMEDICA=IDEMEDICA FROM MED WHERE IDMEDICO=@IDMEDICO

	IF 1=2
	BEGIN
	UPDATE CIT SET
		IDAFILIADO=@IDAFILIADO, NUMCARNET=@NUMCARNET,FECHASOL=GETDATE(), TIPOCITA = 'Cita', TIPOSOLICITUD = 'Web'
		,IDSERVICIO=@IDSERVICIO, ATENCION = 'Ambulatoria', IDCONTRATANTE=@IDCONTRATANTE
		,IDMEDICO=@IDMEDICO, IDPLAN=@IDPLAN, TELEFONOAVISO=@TELEFONOAVISO, USUARIO='KRYSTALOS', TIPOCOPAGO='C'
		,CCOSTO=@CCOSTO, IDEMEDICA=@IDEMEDICA, IDTERCEROCA=@IDCONTRATANTE
	WHERE CONSECUTIVO=@CONSECUTIVO

	UPDATE CIT SET VALORTOTAL = [dbo].[FNK_VLRCITA](CONSECUTIVO)
	WHERE CONSECUTIVO=@CONSECUTIVO
	
	END
END
GO
EXEC SPK_CIT_ADD @CONSECUTIVO = '', @IDAFILIADO = '', @IDMEDICO = '', @IDSERVICIO = ''

