--SELECT * FROM SYS.OBJECTS WHERE NAME LIKE '%CIT%'
IF OBJECT_ID('SPK_CIT','P') IS NOT NULL DROP PROCEDURE SPK_CIT
GO
CREATE PROCEDURE SPK_CIT
	@FDESDE DATETIME,
	@FHASTA DATETIME,
	@FECHASOLICITUD SMALLINT = 0,
	@IDAFILIADO VARCHAR(20) = '',
	@NUMCARNET VARCHAR(20)='',
	@LIBRES SMALLINT = 0, --0: Todas, 1: Solo libres, 2: Citas
	@IDEMEDICA VARCHAR(10)='' 
WITH ENCRYPTION
AS
DECLARE @SQL NVARCHAR(MAX)
BEGIN

	SET @SQL = 'SELECT CIT.*,DBO.FNK_CapitalizarTexto(MED.NOMBRE) Medico FROM CIT LEFT JOIN MED ON MED.IDMEDICO=CIT.IDMEDICO WHERE 1=1 '
	IF @FECHASOLICITUD = 1 
	BEGIN
		SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHASOL) >= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FDESDE,103) +''') '
		SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHASOL) <= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FHASTA,103) +''') '
	END
	ELSE
	BEGIN
		SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHA) >= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FDESDE,103) +''') '
		SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHA) <= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FHASTA,103) +''') '
	END
	IF @LIBRES = 0 OR @LIBRES = 2
	BEGIN
		IF ISNULL(@IDAFILIADO,'')<>'' SET @SQL=' AND IDAFILIADO = '''+@IDAFILIADO+''''
		IF ISNULL(@NUMCARNET,'')<>'' SET @SQL=' AND NUMCARNET = '''+@NUMCARNET+''''
	END
	ELSE
	BEGIN
		SET @SQL = @SQL + ' AND ISNULL(IDAFILIADO,'''') = '''' '
	END
	IF ISNULL(@IDEMEDICA,'')<>''
	BEGIN
		SET @SQL=@SQL + ' AND CIT.IDMEDICO IN (SELECT IDMEDICO FROM MED WHERE IDEMEDICA = ''' + @IDEMEDICA + ''')'
	END
	--PRINT @SQL
	EXECUTE sp_executesql @SQL
END
GO
EXEC SPK_CIT @FDESDE = '1/8/2014', @FHASTA = '1/8/2014', @LIBRES = 1, @IDEMEDICA='550'

--SELECT * FROM CIT WHERE 1=1  AND dbo.FNK_FECHA_SIN_HORA(FECHA) >= dbo.FNK_FECHA_SIN_HORA('01/04/2014')  AND dbo.FNK_FECHA_SIN_HORA(FECHA) <= dbo.FNK_FECHA_SIN_HORA('01/04/2014')  AND ISNULL(IDAFILIADO,'') = '' 
--AND IDMEDICO IN (SELECT IDMEDICO FROM MED WHERE IDEMEDICA = @IDEMEDICA)

--SELECT * FROM CIT WHERE IDAFILIADO IS NULL