IF OBJECT_ID('SPK_USUSUW','P') IS NOT NULL DROP PROCEDURE SPK_USUSUW
GO
CREATE PROCEDURE SPK_USUSUW 
	@ACTION VARCHAR(1) = 'R' -- C,R,U,D
	,@USUARIO VARCHAR(100) = NULL
	,@EMAIL VARCHAR(50) = NULL
	,@ACTIVO BIT = NULL
	,@IDAFILIADO VARCHAR(20) = NULL
WITH ENCRYPTION
AS
DECLARE @SQL AS NVARCHAR(MAX)

--DECLARE @ACTION VARCHAR(1) = 'R' -- C,R,U,D
--DECLARE @USUARIO VARCHAR(100) = NULL
--DECLARE @EMAIL VARCHAR(50) = NULL
--DECLARE @ACTIVO BIT = NULL
--DECLARE @FECHAACTIVO DATETIME = NULL
--DECLARE @IDAFILIADO VARCHAR(20) = NULL
BEGIN
	IF @ACTION = 'C'
	BEGIN
		IF ISNULL(@USUARIO,'')='' OR ISNULL(@EMAIL,'')='' 
		BEGIN	
			RAISERROR ('Parámetros incompletos.', -- Message text.  
				   16, -- Severity.  
				   1 -- State.  
				   );  
			RETURN
		END
		INSERT INTO USUSUW(USUARIO,EMAIL,ACTIVO,FECHAACTIVO,IDAFILIADO)
		SELECT @USUARIO,@EMAIL,ISNULL(@ACTIVO,0), CASE WHEN ISNULL(@ACTIVO,0)=1 THEN GETDATE() ELSE NULL END, @IDAFILIADO
	END

	IF @ACTION = 'R'
	BEGIN
		SET @SQL = 'SELECT * FROM USUSUW WHERE 1=1 '
		IF ISNULL(@USUARIO,'')<>'' SET @SQL=@SQL+' AND USUARIO = '''+@USUARIO+''''
		IF @ACTIVO <> NULL SET @SQL=@SQL+' AND ACTIVO = ' + CAST(@ACTIVO AS VARCHAR)
		IF ISNULL(@IDAFILIADO,'')<>'' SET @SQL=@SQL+' AND IDAFILIADO = '''+@IDAFILIADO+''''
		
		EXECUTE sp_executesql @SQL
	END

	IF @ACTION = 'U'
	BEGIN
		IF ISNULL(@USUARIO,'')='' OR ISNULL(@EMAIL,'')='' 
		BEGIN	
			RAISERROR ('Parámetros incompletos.', -- Message text.  
				   16, -- Severity.  
				   1 -- State.  
				   );  
			RETURN
		END
		UPDATE USUSUW SET EMAIL=@EMAIL,ACTIVO=@ACTIVO,FECHAACTIVO=CASE WHEN ISNULL(@ACTIVO,0)=1 THEN GETDATE() ELSE FECHAACTIVO END,IDAFILIADO = CASE WHEN ISNULL(@IDAFILIADO,'')=1 THEN @IDAFILIADO ELSE IDAFILIADO END
	END

	IF @ACTION = 'D'
	BEGIN
		PRINT 'DELETE'	
		IF ISNULL(@USUARIO,'')='' AND ISNULL(@EMAIL,'')='' 
		BEGIN	
			RAISERROR ('Parámetros incompletos.', -- Message text.  
				   16, -- Severity.  
				   1 -- State.  
				   );  
			RETURN
		END	
		DELETE FROM USUSUW 
		WHERE	USUARIO = CASE WHEN ISNULL(@USUARIO,'')='' THEN USUARIO ELSE @USUARIO END 
		AND		EMAIL = CASE WHEN ISNULL(@EMAIL,'')='' THEN EMAIL ELSE @EMAIL END
	END
END
GO

EXEC SPK_USUSUW 

