IF OBJECT_ID('SPK_MED','P') IS NOT NULL DROP PROCEDURE SPK_MED
GO
CREATE PROCEDURE SPK_MED 
	@IDMEDICO VARCHAR(20) = '',
	@IDEMEDICA VARCHAR(20) = ''
WITH ENCRYPTION
AS
BEGIN
	SELECT * 
	FROM MED
	WHERE IDMEDICO = CASE WHEN ISNULL(@IDMEDICO,'') = '' THEN IDMEDICO ELSE @IDMEDICO END
	AND IDEMEDICA = CASE WHEN ISNULL(@IDEMEDICA,'') = '' THEN IDEMEDICA ELSE @IDEMEDICA END
END
GO

EXEC dbo.SPK_MED @IDEMEDICA='514'