IF OBJECT_ID('SPK_AFI','P') IS NOT NULL DROP PROCEDURE SPK_AFI
GO
CREATE PROCEDURE SPK_AFI
	@IDAFILIADO VARCHAR(15) = NULL
	,@TIPOIDENT VARCHAR(20) = NULL
WITH ENCRYPTION
AS
DECLARE @SQL AS NVARCHAR(MAX)

BEGIN
	SET @SQL = 'SELECT * FROM AFI WHERE 1=1 '
	IF ISNULL(@IDAFILIADO,'')<>'' SET @SQL=@SQL+' AND IDAFILIADO = '''+@IDAFILIADO+''''
	IF ISNULL(@TIPOIDENT,'')<>'' SET @SQL=@SQL+' AND TIPO_DOC = '''+@TIPOIDENT+''''
		
	EXECUTE sp_executesql @SQL
END
GO

EXEC SPK_AFI '00012502028', 'TI' 

