--SELECT * FROM SYS.OBJECTS WHERE NAME LIKE '%CIT%'
IF OBJECT_ID('SPK_CIT','P') IS NOT NULL DROP PROCEDURE SPK_CIT
GO
CREATE PROCEDURE SPK_CIT
	@FDESDE DATETIME = NULL,
	@FHASTA DATETIME = NULL,
	@FECHASOLICITUD SMALLINT = 0,
	@IDAFILIADO VARCHAR(20) = '',
	@NUMCARNET VARCHAR(20)='',
	@LIBRES SMALLINT = 0, --0: Todas, 1: Solo libres, 2: Citas
	@IDEMEDICA VARCHAR(10)='',
	@CUMPLIDA SMALLINT=NULL,
	@IDMEDICO VARCHAR(20)=NULL
WITH ENCRYPTION
AS
DECLARE @SQL NVARCHAR(MAX)
BEGIN
	IF ISNULL(@IDAFILIADO,'')<>'' AND @IDAFILIADO=1 SET @LIBRES=2
	SET @SQL = 'SELECT top 10 CIT.*,DBO.FNK_CapitalizarTexto(MED.NOMBRE) Medico,FECHAESCRITA=CONVERT(VARCHAR,FECHA,103)+'' ''+CONVERT(VARCHAR,FECHA,108)'
	SET @SQL = @SQL + ', SER.DESCSERVICIO AS SERVICIO'
	SET @SQL = @SQL + ' FROM CIT LEFT JOIN MED ON MED.IDMEDICO=CIT.IDMEDICO'
	SET @SQL = @SQL + ' LEFT JOIN SER ON SER.IDSERVICIO=CIT.IDSERVICIO'
	SET @SQL = @SQL + ' WHERE 1=1 '
	

	IF @FECHASOLICITUD = 1 
	BEGIN
		IF @FDESDE IS NOT NULL SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHASOL) >= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FDESDE,103) +''') '
		IF @FHASTA IS NOT NULL SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHASOL) <= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FHASTA,103) +''') '
	END
	ELSE
	BEGIN
		IF @FDESDE IS NOT NULL SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHA) >= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FDESDE,103) +''') '
		IF @FHASTA IS NOT NULL SET @SQL=@SQL + ' AND dbo.FNK_FECHA_SIN_HORA(FECHA) <= dbo.FNK_FECHA_SIN_HORA('''+ CONVERT(VARCHAR,@FHASTA,103) +''') '
	END
	IF @LIBRES = 0 OR @LIBRES = 2
	BEGIN
		IF ISNULL(@IDAFILIADO,'')<>'' SET @SQL=@SQL+' AND IDAFILIADO = '''+@IDAFILIADO+''''
		IF ISNULL(@NUMCARNET,'')<>'' SET @SQL=@SQL+' AND NUMCARNET = '''+@NUMCARNET+''''
	END
	ELSE
	BEGIN
		SET @SQL = @SQL + ' AND ISNULL(IDAFILIADO,'''') = '''' '
	END
	IF ISNULL(@IDEMEDICA,'')<>''
	BEGIN
		SET @SQL=@SQL + ' AND CIT.IDMEDICO IN (SELECT IDMEDICO FROM MED WHERE IDEMEDICA = ''' + @IDEMEDICA + ''')'
	END
	IF @CUMPLIDA IS NOT NULL
	BEGIN
		SET @SQL=@SQL + ' AND CIT.CUMPLIDA = ' + CASE WHEN @CUMPLIDA=0 THEN '0' ELSE '1' END
	END

	IF ISNULL(@IDMEDICO,'')<>''
	BEGIN
		SET @SQL=@SQL + ' AND CIT.IDMEDICO = ''' + @IDMEDICO + ''''
	END
	--PRINT 'SQL = '+@SQL
	EXECUTE sp_executesql @SQL
END
GO
--EXEC SPK_CIT @FDESDE = '1/8/2014', @FHASTA = '1/8/2014', @LIBRES = 1, @IDEMEDICA='550'
EXEC SPK_CIT @IDAFILIADO='690989', @CUMPLIDA=0, @FDESDE='14/09/2017'

--SELECT * FROM CIT WHERE 1=1  AND dbo.FNK_FECHA_SIN_HORA(FECHA) >= dbo.FNK_FECHA_SIN_HORA('01/04/2014')  AND dbo.FNK_FECHA_SIN_HORA(FECHA) <= dbo.FNK_FECHA_SIN_HORA('01/04/2014')  AND ISNULL(IDAFILIADO,'') = '' 
--AND IDMEDICO IN (SELECT IDMEDICO FROM MED WHERE IDEMEDICA = @IDEMEDICA)

--SELECT * FROM CIT WHERE IDAFILIADO IS NULL